title: Miss
author: Netochukwu Anyankah
email: Nanyankah@gmail.com
description: > This is a blog that will narrate my journey into software development.
The resources i used and how long it took me to get to hwere i am.

# social links
twitter_username: on_a_DEvcruise
github_username: neytoe
theme: minima
show_excerpts: true 
